#!/bin/bash
# Script 2: FOSS Package Inspector

PACKAGE="linux-image-$(uname -r)"

if dpkg -l | grep -q $PACKAGE; then
    echo "$PACKAGE is installed."
    dpkg -l | grep $PACKAGE
else
    echo "$PACKAGE is NOT installed."
fi

case $PACKAGE in
    linux*) echo "Linux Kernel: foundation of all modern computing" ;;
    apache2) echo "Apache: powers the open web" ;;
    mysql*) echo "MySQL: backbone of databases" ;;
    firefox) echo "Firefox: open web browser" ;;
    *) echo "Unknown package" ;;
esac
